### ISSUE TITLE
Editing README.md

### ISSUE THREAD

**Issue by LoneRanger1337** [vedant1771/Hactoberfest2021#222]
The Readme.md file contains some typos, better if those could be corrected.

**Comment by Devrajsinh-Jhala** [comment]
Hello @LoneRanger1337 please assign this issue I can fix these issues

**Comment by vedant1771** [comment]
> The Readme.md file contains some typos, better if those could be corrected.

As per the Hactoberfest Instructions, Editing Readme File is not allowed. This may result to termination of repository for hactoberfest. Which means This repository cannot be further counted as "Valid Repository" For Hactoberfest.

**Comment by LoneRanger1337** [comment]
Alright, then I hope after the Fest ends, it could be edited.
