### ISSUE TITLE
Open Source Contribution

### ISSUE THREAD

**Issue by vedant1771** [vedant1771/Hactoberfest2021#50]
For beginners, You can start Contributing to this repository.

**Comment by akash-rao-2001** [comment]
hey! i am new to this.... how may i contribute to this repo?

**Comment by HiruniPerera** [comment]
Hello, I would love to contribute to this project, please tell me how to contribute
Thank you.

**Comment by Saumya2600** [comment]
Why are you only merging pr's of your friends and modifying readme or txt is forbidden. I will report your repository to the hacktober fest team on discord.

**Comment by vedant1771** [comment]
> Why are you only merging pr's of your friends and modifying readme or txt is forbidden. I will report your repository to the hacktober fest team on discord.

It takes some time to See all the Files and then Accept Pull Requests as it is not possible to merge more than 50 PR in one go. I have to manually do it.
